version: '3'
services:
  notebook:
    build:    .
    ports:
    - "80:8888"
    links:
    - mongo
    volumes:
      - ~/Anitha-trial/data:/home/jovyan/work
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dsi_melb
      MONGO_INITDB_ROOT_PASSWORD: padlock
    volumes:
      - ~/Anitha-trial/data/mongodb:/data/db

